language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=test/buildtest.cpp

install:
    - pip install -U platformio
    - platformio lib -g install 5710

script:
    - platformio ci --lib="." --board=esp12e --board=adafruit_feather_m0 Examples/minimal/mu_minimal.cpp
