matrix:
  include:
    - language: python
        python:
            - "2.7"
        sudo: false
        cache:
            directories:
                - "~/.platformio"

        env:
            - PLATFORMIO_CI_SRC=test/buildtest.cpp

        install:
            - pip install -U platformio
            - platformio lib -g install 5710

        script:
            - pio ci --lib="." --project-option="build_flags=-D __ESP__" --board=esp12e Examples/minimal/mu_minimal.cpp

    - language: cpp
      compiler: gcc
      dist: trusty
      sudo: required

      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq valgrind
        - git clone https://github.com/muwerk/ustd Examples/mac-linux/ustd

      # Build steps
      script:
        - cd Examples/mac-linux
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
        - ./muwerk-test
        - valgrind --leak-check=full ./muwerk-test

